const SERVICE_IDENTIFIERS = {
    COMMAND_REGISTRY: Symbol.for('COMMAND_REGISTRY'),
    CONFIGURATION: Symbol.for('CONFIGURATION'),
    MODULE_REGISTRY: Symbol.for('MODULE_REGISTRY')
};

export default SERVICE_IDENTIFIERS;
