const SERVICE_IDENTIFIERS = {
    COMMAND_REGISTRY: Symbol.for('COMMAND_REGISTRY'),
    CONFIGURATION: Symbol.for('CONFIGURATION'),
    MODULE_REGISTRY: Symbol.for('MODULE_REGISTRY'),
    DB_CONNECTION: Symbol.for('DATABASE_CONNECTION'),
    CLIENT: Symbol.for('CLIENT')
};

export default SERVICE_IDENTIFIERS;
